language: python
python:
    - "3.7" 
# command to install dependencies
services:
    - postgresql
env:
    - DJANGO_VERSION= 2.2.4
  global:
      - CC_TEST_REPORTER_ID=525101251cc6ae61db96176c35805f0736b6d6f404d72cb98b548ed2daa4f6a9
    
install:
    - pip install -r requirements.txt

before_script:
    - psql -c 'create database test;' -U postgres
    - python manage.py makemigrations
    - python manage.py migrate
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
 
# command to run tests
script:
    - coverage run --source=iot_project manage.py test
    - bundle exec rspec

after_script:
    - coveralls
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

